name: Building & publishing docs

on:
  push:
    branches: [master,api-docs]

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: "3.11"

      - name: Install requirements
        run: pip install -r docs/requirements.txt

      - name: Install app
        run: pip install .

      - name: Create markdown documents
        run: |
          lazydocs \
              --output-path="./docs/docstrings" \
              --overview-file="README.md" \
              --src-base-url="https://github.com/ohsu-comp-bio/py-tes/blob/master/" \
              --validate \
              tes

      - name: Build docs
        run: mkdocs build && mkdocs gh-deploy --force

