name: Linting and testing

on:
  - push

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        tes-version:
          - "1.0"
          - "1.1"
        
        # Only using Supported Python versions here:
        # https://devguide.python.org/versions
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
          - "3.14"
          - "3.15"

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install requirements
        run: |
          pip install -r requirements.txt
          pip install -r tests/requirements.txt

      - name: Install app
        run: pip install .

      - name: Lint with Flake8
        run: flake8 --max-line-length=120 .

      - name: Run unit tests
        run: |
          pytest \
            --cov=tes/ \
            --cov-branch \
            --cov-report=term-missing \
            --cov-fail-under=99 \
            --ignore=tests/integration

      # Note: Using the same install steps here as in nf-ga4gh plugin
      # https://github.com/nextflow-io/nf-ga4gh/blob/1.4.1/.github/workflows/build.yml#L78-L101
      - name: Install TES Server
        run: |
          # Pinning install script below to stable commit for security/reproducibility
          # Ref: https://docs.github.com/en/actions/reference/security/secure-use#using-third-party-actions
          # Release: https://github.com/calypr/funnel/releases/tag/v0.11.8

          INSTALL_SCRIPT=https://raw.githubusercontent.com/calypr/funnel/4103475e492dec1fd853e9863d0caad15fc504c0/install.sh
          curl -fsSL $INSTALL_SCRIPT | bash -s -- v0.11.8

      - name: Start TES Server
        run: |
          set -euo pipefail
          nohup funnel server run > funnel.log 2>&1 &
          echo $! > funnel.pid
          for i in $(seq 1 10); do
            if curl -fsS http://localhost:8000/service-info >/dev/null 2>&1; then
              echo "Funnel server started"
              exit 0
            fi
            sleep 1
          done
          echo "Funnel server failed to start!"
          cat funnel.log
          exit 1

      - name: Run integration tests
        run: |
          pytest tests/integration
